### ISSUE TITLE
two extensions on the marketplace

### ISSUE THREAD

**Issue by JHenneberg** [yukiuuh/vscode-modern-fortran-formatter#1]
Thanks for the extensions.

There are two extensions on the marketplace which is a bit confusing.

1. 0.0.2: https://marketplace.visualstudio.com/items?itemName=yukiuuh.vscode-modern-fortran-formatter
2. 0.0.3: https://marketplace.visualstudio.com/items?itemName=yukiuuh2936.vscode-modern-fortran-formatter

**Comment by yukiuuh** [comment]
Thanks @JHenneberg .

Both Visual Studio Marketplace accounts are mine, but 2. "yukiuuh2936" should be used.

1. "yukiuuh" is my university SSO account and the account is expired.
So I can't login as "yukiuuh" but the Marketplace account and the extension is still alive...

**Comment by JHenneberg** [comment]
ok that explains it.
